function createfigure(xvector1, ymatrix1)
%CREATEFIGURE(XVECTOR1, YMATRIX1)
%  XVECTOR1:  bar xvector
%  YMATRIX1:  bar matrix data

%  Auto-generated by MATLAB on 11-Aug-2020 01:15:27

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.0578125 0.0619469026548673 0.927083333333333 0.9049822312034]);
hold(axes1,'on');

% Create multiple lines using matrix input to bar
bar1 = bar(xvector1,ymatrix1,'Parent',axes1);
set(bar1(7),'DisplayName','MPC Teórico SS',...
    'FaceColor',[0.266666680574417 0.447058826684952 0.768627464771271]);
set(bar1(6),'DisplayName','MPC Experimental OE',...
    'FaceColor',[0.929411768913269 0.490196079015732 0.192156866192818]);
set(bar1(5),'DisplayName','MPC Experimental ARMAX',...
    'FaceColor',[0.647058844566345 0.647058844566345 0.647058844566345]);
set(bar1(4),'DisplayName','MPC Experimental TF',...
    'FaceColor',[1 0.752941191196442 0]);
set(bar1(3),'DisplayName','PID',...
    'FaceColor',[0.356862753629684 0.607843160629272 0.835294127464294]);
set(bar1(2),'DisplayName','MPC Experimental ARX',...
    'FaceColor',[0.439215689897537 0.678431391716003 0.278431385755539]);
set(bar1(1),'DisplayName','MPC Experimental SS',...
    'FaceColor',[0.149019613862038 0.266666680574417 0.470588237047195]);

% Create ylabel
ylabel({'Integral do erro'},'FontSize',26.4);

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',24,'XTick',[1 2 3 4],'XTickLabel',...
    {'IAE (x10³)','ISE (x10?)','ITAE (x10?)','ITSE (x10?)'},'YGrid','on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','northwest','FontSize',24);

